spring:
  application:
    name: board

  server:
    port: 8080


  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/post
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  jpa:
    hibernate:
      ddl-auto: update

