spring:
  application:
    name: eureka-server

# 유레카 서버 구동시 사용할 포트 변경 -> 8761
server:
  port: 8761

# 자기 자신이 유레카 서버에 클라이언트로 등록 되지 않도록 설정
eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    # serviceUrl:
      #defaultZone: http://${EC2_HOST}/
      #defaultZone: http://${EC2_HOST}/
