spring:
  application:
    name: eureka-server

# ??? ?? ??? ??? ?? ?? -> 8761
server:
  port: 8761

# ?? ??? ??? ??? ?????? ?? ?? ??? ??
eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false