name: Deploy for ci/cd

on:
  push:
    branches:
      - main
      - feat-ec2

jobs:
  cicd-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 17 설치
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. API Gateway 빌드
      - name: Build API Gateway
        working-directory: ./api-gateway
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          ls build/libs  # 빌드된 .jar 파일 확인

      # 4. Eureka Server 빌드
      - name: Build Eureka Server
        working-directory: ./eureka-server
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          ls build/libs  # 빌드된 .jar 파일 확인

      # 5. 빌드된 .jar 파일 이름 변경
      - name: Rename API Gateway build result
        run: |
          mv ./api-gateway/build/libs/*SNAPSHOT.jar ./api-gateway/run-api-gateway.jar
          ls ./api-gateway/build/libs  # 변경된 파일 확인

      - name: Rename Eureka Server build result
        run: |
          mv ./eureka-server/build/libs/*SNAPSHOT.jar ./eureka-server/run-eureka-server.jar
          ls ./eureka-server/build/libs  # 변경된 파일 확인

      # 6. EC2로 API Gateway .jar 파일 업로드
      - name: Upload API Gateway jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: ./api-gateway/run-api-gateway.jar
          target: /home/ubuntu/easyhome

      # 7. EC2로 Eureka Server .jar 파일 업로드
      - name: Upload Eureka Server jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: ./eureka-server/run-eureka-server.jar
          target: /home/ubuntu/easyhome

      # 8. EC2 접속 후 API Gateway 및 Eureka Server 가동
      - name: SSH to EC2 and start servers
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            # 기존 프로세스 종료
            sudo fuser -k -n tcp 8080 || true  # API Gateway 포트 종료
            sudo fuser -k -n tcp 8761 || true  # Eureka Server 포트 종료

            # API Gateway 서버 실행
            rm -rf /home/ubuntu/easyhome/api-gateway
            mkdir -p /home/ubuntu/easyhome/api-gateway
            mv /home/ubuntu/easyhome/run-api-gateway.jar /home/ubuntu/easyhome/api-gateway/run-api-gateway.jar
            cd /home/ubuntu/easyhome/api-gateway
            nohup java -jar run-api-gateway.jar > ./output-api-gateway.log 2>&1 &

            # Eureka Server 서버 실행
            rm -rf /home/ubuntu/easyhome/eureka-server
            mkdir -p /home/ubuntu/easyhome/eureka-server
            mv /home/ubuntu/easyhome/run-eureka-server.jar /home/ubuntu/easyhome/eureka-server/run-eureka-server.jar
            cd /home/ubuntu/easyhome/eureka-server
            nohup java -jar run-eureka-server.jar > ./output-eureka-server.log 2>&1 &

            # 정리 작업
            rm -rf /home/ubuntu/easyhome/run-api-gateway.jar
            rm -rf /home/ubuntu/easyhome/run-eureka-server.jar
