name: easy home

on:
  push:
    branches:
      - main
      - feat-ec2
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. JDK 17 설치
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. 빌드 (API Gateway)
      - name: Build API Gateway
        working-directory: ./api-gateway
        run: |
          chmod +x ./gradlew  # gradlew 실행 권한 부여
          ./gradlew clean build -x test
          ls build/libs  # 빌드된 .jar 파일 확인

      # 4. 빌드 (Eureka Server)
      - name: Build Eureka Server
        working-directory: ./eureka-server
        run: |
          chmod +x ./gradlew  # gradlew 실행 권한 부여
          ./gradlew clean build -x test
          ls build/libs  # 빌드된 .jar 파일 확인

      # 5. SSH를 통해 EC2에 연결하여 업로드
      - name:  EC2에 연결하여 업로드
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: api-gateway-0.0.1-SNAPSHOT.jar, eureka-server-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/demo/home


            
