name: easy home

on:
  push:
    branches:
      - main
      - feat-docker
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. JDK 17 설치
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. 애플리케이션 빌드 (API Gateway)
      - name: Build API Gateway
        working-directory: ./api-gateway
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          ls build/libs  # 빌드된 .jar 파일 확인

      # 4. 애플리케이션 빌드 (Eureka Server)
      - name: Build Eureka Server
        working-directory: ./eureka-server
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          ls build/libs  # 빌드된 .jar 파일 확인

      # 5. SSH를 통해 EC2에 연결하여 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            
            cd ~/easy-home || git clone https://github.com/your-repo/easy-home.git
            cd easy-home
            java -version

            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk

            cd api-gateway
            ./gradlew clean build -x test
            cd ../eureka-server
            ./gradlew clean build -x test

            pkill -f 'java -jar' || true
            nohup java -jar api-gateway/build/libs/api-gateway-0.0.1-SNAPSHOT.jar &
            nohup java -jar eureka-server/build/libs/eureka-server-0.0.1-SNAPSHOT.jar &
            echo "Deployment Complete"
