name: easy home

on:
  push:
    branches:
      - main
      # - feat-docker

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 17 설치
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. 빌드 (API Gateway)
      - name: Build API Gateway
        working-directory: ./api-gateway
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          pwd
          ls
          ls ./build/libs

      # 4. 빌드 (Eureka Server)
      - name: Build Eureka Server
        working-directory: ./eureka-server
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          pwd
          ls
          ls ./build/libs

      # 5. SSH를 통해 EC2에 연결하여 업로드
      - name: EC2에 연결하여 업로드 (유레카)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: ./eureka-server/build/libs/eureka-server-0.0.1-SNAPSHOT.jar, ./api-gateway/build/libs/api-gateway-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/demo/home

      - name: EC2에서 업로드된 파일 확인
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            ls -l /home/ubuntu/demo/home/eureka-server/build/libs/
            ls -l /home/ubuntu/demo/home/api-gateway/build/libs/

      - name: 서버 접속
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/server/easy_home
            mkdir -p /home/ubuntu/server/easy_home
            mv /home/ubuntu/demo/home/eureka-server/build/libs/eureka-server-0.0.1-SNAPSHOT.jar /home/ubuntu/server/easy_home/eureka-server-0.0.1-SNAPSHOT.jar
            mv /home/ubuntu/demo/home/api-gateway/build/libs/api-gateway-0.0.1-SNAPSHOT.jar /home/ubuntu/server/easy_home/api-gateway-0.0.1-SNAPSHOT.jar
            cd /home/ubuntu/server/easy_home
            sudo fuser -k -n tcp 8761 || true
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar eureka-server-0.0.1-SNAPSHOT.jar > ./output.log 2>&1 &
            nohup java -jar api-gateway-0.0.1-SNAPSHOT.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/server/demo