name: easy home

on:
  push:
    branches:
      - main
      - feat-docker
      - feat-ec2
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. JDK 17 설치
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. 애플리케이션 빌드 (API Gateway)
      - name: Build API Gateway
        working-directory: ./api-gateway
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          ls build/libs  # 빌드된 .jar 파일 확인

      # 4. 애플리케이션 빌드 (Eureka Server)
      - name: Build Eureka Server
        working-directory: ./eureka-server
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          ls build/libs  # 빌드된 .jar 파일 확인

      # 5. SSH를 통해 EC2에 연결하여 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # EC2에서 코드 클론 및 디렉토리 설정
            rm -rf ~/easy_home
            cd ~/easy_home || git clone --single-branch --branch feat-ec2 https://github.com/RookiesTeam6/easy_home.git
            cd easy_home
            java -version
            
            # OpenJDK 17 설치
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            
            # API Gateway 및 Eureka Server 빌드
            cd api-gateway
            ./gradlew clean build -x test
            cd ../eureka-server
            ./gradlew clean build -x test
            
            # JWT_SECRET_KEY 환경 변수 설정
            export JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}"
            
            # 기존 Java 프로세스 종료
            pkill -f 'java -jar' || true
            
            # API Gateway와 Eureka Server 실행 (JWT_SECRET_KEY 환경 변수 전달)
            nohup java -jar -DJWT_SECRET_KEY=$JWT_SECRET_KEY api-gateway/build/libs/api-gateway-0.0.1-SNAPSHOT.jar &
            nohup java -jar -DJWT_SECRET_KEY=$JWT_SECRET_KEY eureka-server/build/libs/eureka-server-0.0.1-SNAPSHOT.jar &
            
            echo "Deployment Complete"